namespace ShopKeeper.Domain.Entities;

using ShopKeeper.Domain.Common;
using ShopKeeper.Domain.Enums;

/// <summary>
/// Append-only ledger row for every stock movement. Nothing should ever update or delete a
/// row here - to correct a mistake, add a compensating transaction. See section 40 of the
/// product spec: "Every inventory change must create an inventory transaction. Never silently
/// change stock quantities."
/// </summary>
public class InventoryTransaction : BaseEntity, ITenantEntity
{
    public Guid BusinessId { get; set; }
    public Business Business { get; set; } = default!;

    public Guid ProductId { get; set; }
    public Product Product { get; set; } = default!;

    public Guid BranchId { get; set; }
    public Branch Branch { get; set; } = default!;

    public InventoryTransactionType Type { get; set; }

    /// <summary>Positive for increases (initial stock, adjustment up, refund), negative for decreases (sale, adjustment down).</summary>
    public int QuantityChange { get; set; }

    /// <summary>Snapshot of ProductStock.QuantityOnHand immediately after this transaction, for audit clarity.</summary>
    public int QuantityAfter { get; set; }

    public string Reason { get; set; } = default!;

    /// <summary>e.g. "Sale" + SaleId, when this transaction was generated by another record rather than a manual adjustment.</summary>
    public string? ReferenceType { get; set; }
    public Guid? ReferenceId { get; set; }

    public Guid CreatedByUserId { get; set; }
}
